name: flutterex
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
#  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.9

  http: ^0.13.4
  http_interceptor: ^1.0.2

  json_annotation: ^4.5.0

  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

  get: ^4.6.1
  get_storage: ^2.0.3

  logger: ^1.1.0
  webview_flutter: ^3.0.4

#  url_launcher: ^6.0.6
#  share_plus: ^4.0.4
  printing: ^5.3.0
  flutter_html_to_pdf: ^0.7.0
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9

  extended_image: ^6.2.1
  loading_animations: ^2.1.0
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  firebase_crashlytics: ^2.8.1
  firebase_storage: ^10.2.17

#  auto_size_text: ^3.0.0

  #  webview_flutter: ^3.0.0
#  webview_flutter:
    #      path: ../webviewflutter_bitbucket/webview_flutter
#    git:
#      url: https://wjdev-004@bitbucket.org/wjdev-004/webviewflutter.git
#      path: webview_flutter
#      ref: master

#    git:
#      url: https://wjdev-004@bitbucket.org/wjdev-004/webview_flutter.git

#    git:
#      url: http://19002135:19002135!@scm.wjthinkbig.com:9444/r/MiddleClientLib.git
#      path: webview_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: NanumSquare
      fonts:
        - asset: assets/fonts/nsrl.ttf
          weight: 400
        - asset: assets/fonts/nsrr.ttf
          weight: 500
        - asset: assets/fonts/nsrb.ttf
          weight: 700
        - asset: assets/fonts/nsreb.ttf
          weight: 800